baseURL = 'https://aoe4.christitus.com/'
languageCode = 'en-us'
title = 'House of Titus'
copyright = "2025 House of Titus"
theme = 'diary'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
subtitle = "Guides, Gameplay, and Entertainment"
enableGiscus = true
enableOpenGraph = true
title = "House of Titus" # will set 'og:site_name'
description = "Age of Empires IV guides, gameplay, and general entertainment"  # will set 'og:description'

[params.social]
youtube = "https://www.youtube.com/house_of_titus"
twitch = "https://www.twitch.tv/house_of_titus"

[taxonomies]
   tag = "tags"
   category = "categories"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
   data-repo="christitustech/aoe4"
   data-repo-id="R_kgDOQVtfYg"
   data-category="Announcements"
   data-category-id="DIC_kwDOQVtfYs4CxynQ"
   data-mapping="title"
   data-strict="0"
   data-reactions-enabled="1"
   data-emit-metadata="0"
   data-input-position="bottom"
   data-theme="preferred_color_scheme"
   data-lang="en"
   crossorigin="anonymous" 

[[menu.main]]
url = "/"
name = "Strategies"
weight = 2
[[menu.main]]
url = "/games/"
name = "Games"
weight = 1
